### ISSUE TITLE
AttributeError: type object 'Color' has no attribute 'to_tuple'

### ISSUE THREAD

**Issue by yashgharat** [ty-porter/RGBMatrixEmulator#64]
I think in commit 487ed18 you got rid of `to_tuple()` and that broke the tkinter adapter. I am now getting the error 

```
  File "RGBMatrixEmulator/adapters/tkinter_adapter.py", line 48, in draw_to_screen
    self.__canvas.itemconfig(shape_id, fill=Color.to_hex(pixel))
  File "RGBMatrixEmulator/graphics/color.py", line 18, in to_hex
    return "#%02x%02x%02x" % Color.to_tuple(pixel)
AttributeError: type object 'Color' has no attribute 'to_tuple'
```

**Comment by yashgharat** [comment]
Jsut confirmed, it works in version `0.10.0`, but broken in `0.11.0`

**Comment by ty-porter** [comment]
Thanks for the report, I was able to reproduce easily and fix is forthcoming soon in 0.11.1.

**Comment by ty-porter** [comment]
Resolved by #65
